services:
  # SMTP server to capture outgoing emails
  mailhog:
    image: docker.io/mailhog/mailhog
    logging:
      driver: 'none'  # disable to verbose logs
    networks:
      default:
        aliases:
          - mailhog.localhost

  redis:
    image: bitnami/redis:7.2
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      default:
        aliases:
          - redis.localhost

  postgres:
    image: bitnami/postgresql:16
    environment:
      - ALLOW_EMPTY_PASSWORD="no"
      - POSTGRESQL_POSTGRES_PASSWORD=root1234
      - POSTGRESQL_DATABASE=reeder
      - POSTGRESQL_USERNAME=reeder
      - POSTGRESQL_PASSWORD=reeder1234
    networks:
      default:
        aliases:
          - postgres.localhost

  reeder:
    image: devcontainer
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
      target: devcontainer
    read_only: true
    depends_on:
      - redis
      - postgres
      - mailhog
    volumes:
      - .:/app
    tmpfs:
      - /var/tmp:mode=770,uid=1000,gid=1000
    expose:
      - 8000
    ports:
      - "5678:5678" # debug port
    networks:
      default:
        aliases:
          - reeder.localhost
