services:
  traefik:
    image: "traefik:v2.4"
    restart: on-failure
    command:
      # - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  mailhog:
    labels:
      # These labels enable traefik to route traffic to the container
      - "traefik.enable=true"
      - "traefik.http.routers.email.rule=Host(`mailhog.localhost`)"
      - "traefik.http.routers.email.entrypoints=web"
      - "traefik.http.services.email.loadbalancer.server.port=8025"
    entrypoint: ["/bin/sh", "-c", "MailHog &>/dev/null"]

  postgres:
    ports:
      - "5432:5432"
    volumes:
      - /mnt/data/postgresql/data:/bitnami/postgresql

  reeder:
    labels:
      # These labels enable traefik to route traffic to the container
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`reeder.localhost`)"
      - "traefik.http.routers.app.entrypoints=web"
      - "traefik.http.services.app.loadbalancer.server.port=8000"
