# Generated by Django 4.2.15 on 2024-09-24 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RssFeed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("url", models.URLField(db_index=True, default="", unique=True)),
                ("name", models.CharField(blank=True, default="", max_length=100)),
                ("lastmodified", models.DateTimeField(auto_now=True, db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name="RssArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("url", models.URLField(db_index=True, default="")),
                ("snippet", models.CharField(blank=True, default="", max_length=500)),
                ("is_read", models.BooleanField(default=True)),
                ("lastmodified", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "feed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="rssfeeds.rssfeed"
                    ),
                ),
            ],
            options={
                "unique_together": {("feed", "url")},
            },
        ),
    ]
